### ISSUE TITLE
Summary of questions before fillling

### ISSUE THREAD

**Issue by matu3ba** [ds-wizard/ds-wizard#167]
Showing 
1.summary of questions before filling
and 
2. the difference to the known core dataset would be ideal.
I do not have a good decision support on which model and questionaire to use.

**Comment by vknaisl** [comment]
Hello matu3ba,

thanks for the feedback.

1. That can be a little bit more tricky. Our vision is to show just a few questions (not to terrify users) and after a user replies to some questions, we will show him more. So the summary of questions doesn't make sense here. Or if it does for you, could you please explain it to me more?

2. This issue is totally in our plan but it's not currently put in the roadmap. You can watch the progress here (https://ds-wizard.atlassian.net/browse/DSW-92?searchSessionId=df31ff84-d2ce-46e3-8c83-7e526ef93d51&searchContainerId=10001&searchContentType=issue&searchObjectId=10091).

Vojtech
