### ISSUE TITLE
New question type: Multiple Answers from predefined options 

### ISSUE THREAD

**Issue by korbinib** [ds-wizard/ds-wizard#187]
Users report frequently that there is a question type missing, allowing multiple selections from predefined answers. (Example in DSW KM: Contributor Roles)

**Comment by MarekSuchanek** [comment]
Thank you for the idea, we already have it in Backlog in JIRA: https://ds-wizard.atlassian.net/browse/DSW-397

We need to discuss this feature in a higher detail. Currently, it is possible to have a list question with a single option question - semantically you select multiple answers for the question and it even allows to have followups. It would get complicated in case of checkboxes to show which followup questions belong to which option as the context is crucial. On the other hand, this current solution allows you to "check" a single option multiple times (don't know why someone would do that, but it is possible).

Do you (or your users) please have any more thoughts about this? It would be really helpful to find an optimal solution.

Regarding the common KM - @rwwh do we want to update it so contributor can have multiple roles?

**Comment by rwwh** [comment]
I have had several cases where I would have liked to have this feature. Semantically, your solution has the same possibility, but it does not feel natural.

I see two options of getting closer to the interface we need:
1. A real multi-select. Any followup questions can visually be just "appended" to the bottom; their numbering could be used to trace back where it comes from, and internally it is clear, but I think this is less important for the user. Imagine one contributor type needs a postal address, the other one an e-mail; who cares that they both are asked if both answers are selected.
2. A list with an integration or a built-in restricted vocabulary. This would require typing in a text box (unless we recognize limited lists and render them differently), and can not ask for e-mail vs postal address for different options, because it is not an option question.

My preference would be the first.

**Comment by MarekSuchanek** [comment]
We moved this idea to new service for feature requests: [ideas.ds-wizard.org (#1)](https://ideas.ds-wizard.org/posts/1/multichoice-questions)

You can vote for this feature and discuss it there.
