### ISSUE TITLE
Research Domain list (Question 4 under General Information about Participant) should not contain a list of repositories

### ISSUE THREAD

**Issue by rduerr** [ds-wizard/ds-wizard#192]
**Describe the bug**

While trying to enter information for the Polar Data Enhancement Research group (POLDER) project (FAIR Convergence Matrix Questionnaire, 3.0.0) I tried to enter a research Domain for our group; but all the entries are actually repositories not domains!  Worse yet our group covers all possible domains so I was looking for the top node of an ontology of academic domains.  

**How to reproduce**
Steps to reproduce the problem:
1. Go to https://fair-matrix.ds-wizard.org
2. Click on Questionnaires
3. Go to General Information about Participant
4. Scroll down to 4 Research Domain
5. Start typing and notice that all of the suggested domains are actually repositories or at least not domains!

**Expected behavior**
If you ask for a research domain, I expect to get a list of domains like biology, geology, etc. not a list of repositories

**Screenshots**

![image](https://user-images.githubusercontent.com/1544892/88340043-4b917100-ccf8-11ea-9450-962986bbaba3.png)

**DS Wizard deployment:**

 - Browser [Firefox 78.0.2]

**Comment by MarekSuchanek** [comment]
Dear @rduerr, thanks for your report... It took us a while because of discussion with authors of this specific Knowledge Model and also maintainers of FAIR Matrix instance (currently FIP Wizard). A lot of work is currently being done to improve the FIP questionnaire and allow production of nanopublications. Research domains will be a property of a Community selected outside of the Wizard (for its own nanopublication).

The initial stuff should be ready during October with further development til end of this year.
