### ISSUE TITLE
Error on submission of report

### ISSUE THREAD

**Issue by elijoe** [ds-wizard/ds-wizard#193]
**The Question**
Each time i try to submit a report, i get this error
**DS Wizard part**
Unable to submit the report.
Store data in configure triple store and update related Metadata in Fair Data point

**Additional context**
Add any other context or screenshots related to the question.
[Error on dsw.docx](https://github.com/ds-wizard/ds-wizard/files/5293315/Error.on.dsw.docx)

**Comment by MarekSuchanek** [comment]
Hello @elijoe,

This issue is not related directly to the DSW itself. You need to contact the maintainer of that VODAN-in-a-Box instance.

My suggestion for him/her is to check whether all the Docker containers are running (using `docker-compose ps`) and eventually look in the logs (using `docker-compose logs`). Probably submission service or target triple stores are **not running or are misconfigured**. Unfortunately, based on this information I cannot provide more assistance 😞
