### ISSUE TITLE
concept of 'level' as in requestedLevel

### ISSUE THREAD

**Issue by froggypaule** [ds-wizard/ds-wizard#199]
**The Question**
what is meant by 'level'

**DS Wizard part**
all

**Additional context**
Since events/items are structured into a parent-child relationship, what is the meaning of level, as in 'requestedLevel'. I did not find any doc in this regard.... thanks.

**Comment by MarekSuchanek** [comment]
That should be visible only in KM JSON representation... it is "desirability level", currently there are just 4:

0 = never
1 = before proposal submission
2 = before DMP submission
3 = before finishing the project

But in the future, we plan to make it more generic and allow to define custom levels/phases. It is not named "phases" due to this plan to make it generic.

**Comment by froggypaule** [comment]
Many thanks Marek ! I close this now.
