### ISSUE TITLE
colons ':' in km or kmId results in confused behaviour

### ISSUE THREAD

**Issue by froggypaule** [ds-wizard/ds-wizard#204]
**Describe the bug**
Adding colons ':' in the name of the km name (id or kmId) results in unexpected behaviour.

**How to reproduce**
Steps to reproduce the problem:
1. create a km from a json file whose name contains columns (for example, I suffixed the name with 'date date +%FT%T')
  -- note that uploading the file and creating the km does not throw an error.
1. create a project from this km
2. go to the project's settings
3. go to settings to import a template: 
   here it apparently tries to load a km: it says 'km could not be loaded' or something to that effect
4. in the logs we see

dsw_server    | [Warn ] [I:4f9a9661-d4c2-4f17-ab76-f3482d826e67] [T:------------------------------------] [API         ] 400 Bad Request GET /templates/suggestions?page=0&size=20&pkgId=global:bioimage-structure-2021-01-28T16:23:41:0.0.0
5. redoing steps 1 to 3 after having removed the colons ends in success in loading the template.

**DS Wizard deployment:**
 - stand alone (docker)
 - Browser [e.g. chrome, safari] (inc. version, if relevant)

Many thanks.

**Comment by MarekSuchanek** [comment]
Indeed, KM ID can contain only alphanumeric symbols and dash, organization ID can contain alphanumeric symbols and dot. See here: https://docs.ds-wizard.org/en/latest/dev/schemas/kmp.html#knowledge-model-id

You can try to validate your KM, using the schema from docs. But it is intended mainly for "documenting" rather than "validating". Manually done JSONs are not the supported way how to do things with DSW (although it is a possible way).

**Comment by froggypaule** [comment]
Yes thanks Marek. Just wanted to point out the bug (':' validated at the time of importing the json file).

**Comment by MarekSuchanek** [comment]
I see, thanks... I added that to our JIRA: DSW-1006
