### ISSUE TITLE
how to 'clean' the database

### ISSUE THREAD

**Issue by froggypaule** [ds-wizard/ds-wizard#218]
**The Question**
How to force remove projects.

**DS Wizard**
3.1.0 self-installed

**Additional context**
- did try to migrate questionnaires who migration failed due to various config errors (see #216 for example); see 
![Screenshot from 2021-07-20 15-13-00](https://user-images.githubusercontent.com/47455219/126330324-5d355746-e182-453a-a2c0-14f550e3d925.png)
for example
- these questionnaires' migration seem to be in a stalled state, but one cannot remove them (nor proceed or cancel the migration); see 
![Screenshot from 2021-07-20 15-13-40](https://user-images.githubusercontent.com/47455219/126330432-4708464d-b28f-4d10-8e5e-55b3058474f3.png)
when trying to 'continue migration'

**Objective**
Clean the db.

Many thanks!

**Comment by MarekSuchanek** [comment]
Hello,
thanks for reporting your issue. We are sorry that you got into this unwanted situation. However, adding a button with "Force delete" functionality would just confuse regular users. It seems like you get into some strange inconsistent state probably due to some misconfiguration. However, as have an access to the DB, you can delete it manually from the DB... In this case, search for questionnaire migration with the specific UUID that is part of the URL.

**Comment by froggypaule** [comment]
Good point Marek! thanks!
