### ISSUE TITLE
object CrossReference in document_worker

### ISSUE THREAD

**Issue by froggypaule** [ds-wizard/ds-wizard#232]
**The Question**
The question you want to ask us.
It seems that object CrossReference is missing from this [page](https://github.com/ds-wizard/document-worker/blob/master/support/DocumentContext.md#listquestion)

**Comment by MarekSuchanek** [comment]
The issue is that the `CrossReference` is still somewhat *hidden feature* (not even feature I would say, more like relict) - you cannot create nor edit it in KM editor and it was never rendered in the questionnaire nor documents. It is there because such links were in the original Rob's mindmap, but we still don't know how to implement it properly - if you have some use cases for cross references and have ideas how it should work in questionnaires, please add it to https://ideas.ds-wizard.org

**Comment by froggypaule** [comment]
Ok, no worries, it is just that I saw this when rewriting the km-insight template. It's all fine by me.
