### ISSUE TITLE
Error: unable to get questionnaires

### ISSUE THREAD

**Issue by wvranken** [ds-wizard/ds-wizard#242]
**Describe the bug**

For the https://rnact.ds-wizard.org/projects page, we cannot access the project any more, but get an 'Error Unable to get Questionnaires.' message.

**How to reproduce**
Steps to reproduce the problem:
1. Go to https://rnact.ds-wizard.org/projects

**Expected behavior**

A list of the projects that we can access (there are projects that we made previously). The knowledge models still work.

**Screenshots**

**DS Wizard deployment:**
 - Instance [e.g. demo.ds-wizard.org, local, or our custom]
 - Browser [e.g. chrome, safari] (inc. version, if relevant)

In case of your own instance, describe the setup, i.e., if you are using Docker or build DSW from source, what version are you using, etc.

We think there might have been an update that might have caused this issue? Also a template was created, that might have been an issue.

**Additional context**

**Comment by MarekSuchanek** [comment]
Dear @wvranken, it seems that there is an issue with computing indications for [one project](https://rnact.ds-wizard.org/projects/ceec37d6-2f78-4e87-9765-5e7c5dff35e9). We were not able to quickly see what causes the issue, to allow listing projects, we temporarily removed all the reply events there. Please do not use this project as we will put the replies back once we figure out the cause (let's keep this issue open).

Sorry for the inconvenience!

**Comment by MarekSuchanek** [comment]
@wvranken is it possible that you added replies to that project via API, e.g. by using some custom script?

**Comment by mddevignes** [comment]
Hello, I checked the problematic project Test_KM4_bis.  In fact it was one of our attempt (Malika and me) to quickly create and test a template project (just as Test_RNActprefilledDMP_KM4). We did not use any particular script to create it.
However, it is true that we have modified the underlying knowledge model KM4 a lot after that. 
Recently and after discussing with Paulette we decided to start from one of our first KM rather than building on modified versions in which not all modifications have been published... 
So, if this can help, you can delete the problematic project Test_KM4_bis. We will not use it anymore.
Sorry for the disturbance and thank you for identifying the bug.
Best
Marie-Dominique
