### ISSUE TITLE
FAIRsharing integration 

### ISSUE THREAD

**Issue by froggypaule** [ds-wizard/ds-wizard#280]
### What is your question?

First, apologies to @MarekSuchanek as we discussed this ages ago but I let it drop and only coming back to it now.

DSW self-hosted, V3.23.

Following FAIRsharing's [doc](https://fairsharing.org/API_doc), this works
```
import requests
import json

url = "https://api.fairsharing.org/users/sign_in"

payload={"user": {"login":"plieby","password":"xxxx"} }
headers = {
  'Accept': 'application/json',
  'Content-Type': 'application/json'
}

response = requests.request("POST", url, headers=headers, data=json.dumps(payload))

# Get the JWT from the response.text to use in the next part.
data = response.json()
jwt = data['jwt']
url = "https://api.fairsharing.org/fairsharing_records/1"

headers = {
  'Accept': 'application/json',
  'Content-Type': 'application/json',
  'Authorization': "Bearer {0}".format(jwt),
}

response = requests.request("GET", url, headers=headers)
print(response.text)
```

This works too, making it a one call pass (jwt takes the saved value from above)
```
jwt = "xxx"
url = "https://api.fairsharing.org/search/fairsharing_records?fairsharing_registry=standard&q=Mouse Adult Gross Anatomy Ontology"
response = requests.request("POST", url, headers=headers)
print(response.json())
```

**Comment by froggypaule** [comment]
Following this, I thought of saving apiUrl and apiKey in an integration.yml file, as follows
```
fairsharing:
  apiKey:  xxx
  apiUrl: https://api.fairsharing.org

```

but this gives me the following error

![Screenshot from 2023-05-17 09-27-21](https://github.com/ds-wizard/ds-wizard/assets/47455219/2dfd31b0-f5ec-48e4-af9a-de3a41ac5690)

So obviously I don't know how to handle this.

**Comment by froggypaule** [comment]
Also, I note that the configuration found in the Common DSW KM is different from the requests I built as explained in the FAIRsharing doc:
![Screenshot from 2023-05-17 09-28-52](https://github.com/ds-wizard/ds-wizard/assets/47455219/c3b82336-a164-4606-ba7d-1732e574a22d)

so, 
```
${apiUrl}/search/?q=${q}&registry=${registry}
```
instead of
```
url = "https://api.fairsharing.org/search/fairsharing_records
url = "https://api.fairsharing.org/search/fairsharing_records?fairsharing_registry=standard&q=Mouse Adult Gross Anatomy Ontology"

```
```
'Authorization': "Bearer {0}".format(jwt),
```
instead of Api-Key, and 
```
response = requests.request("POST", url, headers=headers)
```
instead of `GET`

So I am a bit confused .... ;) thanks for helping out.

**Comment by MarekSuchanek** [comment]
Indeed, the old approach does not work anymore with FAIRsharing as they changed the API and mainly its authentication procedure. DSW cannot make additional authentication requests before (potentially each) API query... to overcome this, we developed a simple proxy service (there are still some things to improve, but it works well for now).

1. You need to have account to FAIRsharing with `username` and `password` (and related to an organisation).
2. Then, you should use BASE64 to encode: `username:password` (e.g. run `echo -n 'username:password' | base64`)
3. Finally, you should have your `integration.yml` like this:

```yaml
fairsharing:
  apiUrl: https://fairsharing4dsw.ds-wizard.org/legacy
  apiKey: "<base64credentials>"
```

The proxy basically does the two steps and imitates the way how the old FAIRsharing API worked (filtering and result format). We plan to improve it with some caching later on and improve documentation, but not a huge priority at this point.

You can test it to "fake" the request from DSW:

```
curl --header "Accept: application/json" \
     --header "Api-Key: <base64credentials>" \
     "https://fairsharing4dsw.ds-wizard.org/legacy/search/?q=banana&registry=database"
```

Final remark, the proxy is allowed to be used only for DSW purposes (integration from DSW or testing it in order to use it in DSW).

Do you have any suggestion where would be the best place to document this?

**Comment by froggypaule** [comment]
Hello Marek!
Ha!! this makes sense: that we are using a legacy proxy, I understand now you configuration.
I suggest to document this in https://guide.ds-wizard.org/en/latest/more/development/integration-questions/integration-api.html where there is a FAIRsharing example. So that people like me don't keep asking the same question... ;)

**Comment by froggypaule** [comment]
One more thing: where is the integration.yml supposed to sit? because in my case, it is still not read properly. 
Otherwise, yes, the curl cmd is working!

**Comment by MarekSuchanek** [comment]
It should be in `/app/config/integration.yml` (next to the [app configuration file](https://github.com/ds-wizard/dsw-deployment-example/blob/main/docker-compose.yml#L14)). But you can also configure it in Settings (see [guide](https://guide.ds-wizard.org/en/latest/application/administration/settings/content/knowledge-models.html#integration-config)).

**Comment by froggypaule** [comment]
!!!! Victory!!! many thanks :)
