### ISSUE TITLE
the label 'project template' or 'project model'

### ISSUE THREAD

**Issue by froggypaule** [ds-wizard/ds-wizard#281]
### What is your question?

I am wondering: a DSW project is a questionnaire (maybe a model of a questionnaire) + sharing options + output model + documents.
Is 'project template' really 
![Screenshot from 2023-06-07 14-10-11](https://github.com/ds-wizard/ds-wizard/assets/47455219/30297ed7-f165-4951-8541-857a5adcde3e)

correct? shouldn't we rather say 'questionnaire template'? 

I am asking this because I try to establish a clear mapping between commonly used French terms and DSW terms. 

Also, btw, this is how the screen above shows in French:
![Screenshot from 2023-06-07 14-15-57](https://github.com/ds-wizard/ds-wizard/assets/47455219/399252c6-02e3-4bc9-bd20-ea7bc98b147c)

Not very nice... what do you recommend we do? thanks!

**Comment by MarekSuchanek** [comment]
Hi @froggypaule, there are two points to this:

1. the translations should be as close as the original language (keeping it clear but consistent), e.g. in case _Custom_ is used somewhere else, it will use your translation there as well (can be in different context)
2. it is a _Project Template_ because it prepares a project (questionnaire, settings, comments, etc.) and _Custom_ allows in this context to create a project in custom way (KM, tags, empty questionnaire, settings, etc.)

**Comment by froggypaule** [comment]
Hello @MarekSuchanek , 
Ok for using the term 'project template', I was just wondering.
For the translation, I am all fine with that. 
I'll close this :)
