### ISSUE TITLE
S3 service publicly available in 3.20?

### ISSUE THREAD

**Issue by jokermanse** [ds-wizard/ds-wizard#282]
### What is your question?

We are having some problems with document downloads after (finally) upgrading our test server to 3.20.
Could you please clarify what publicly available means in this case, i.e. if the s3 endpoint in the server configuration (s3.url) should now actually be a public link, and not an internal link, like http://minio:9000 (as in the example config)?   

Thanks!

**Comment by MarekSuchanek** [comment]
Hello @jokermanse, yes since 3.20 this s3.url needs to be publicly accessible (preferably through HTTPS proxy, just as DSW API) as downloads use S3 temporary links. For example, if you have `api.dsw.example.tld`, it could be served on `s3.dsw.example.tld`.

This provides a good documentation on [how to setup proxy for minio (and exposing it)](https://min.io/docs/minio/linux/integrations/setup-nginx-proxy-with-minio.html).

It starts to seem to be quite unfortunate as several deployments had issue with it; however, it was a step to improve the security (avoiding tokens being in URLs). We will take a look at this if it can be somehow improved while secure.
